// examples/vite-vue/src/components/mixed-token.vue
<template>
  <div>
    <h2>Mixed Token Read</h2>
    <form @submit.prevent="handleReadSubmit">
      <label for="address">Contract Address: <input id="address" v-model="readAddress" type="text"
          :placeholder="zeroAddress" /></label>
      <button type="submit">Read</button>
    </form>
    <p>Get Raising Token: {{ readRaisingToken }}</p>
    <p>Get Admin: {{ readAdmin }}</p>
    <p>Get Metadata: {{ readMetadata }}</p>
    <p>Get Tax Rate: {{ readTaxRate }}</p>
    <p>Get Treasury: {{ readTreasury }}</p>
    <p>Get Estimate Mint: {{ readEstimateMint }}</p>
    <p>Get Estimate Burn: {{ readEstimateBurn }}</p>
    <p>Get Estimate Mint Need: {{ readEstimateMintNeed }}</p>

    <h2>Mixed Token Write</h2>
    <form @submit.prevent="handleWriteSubmit">
      <label for="address">
        Contract Address:
        <input id="address" v-model="writeAddress" type="text" :placeholder="zeroAddress">
      </label>

      <label for="raisingAmount">
        Raising Amount:
        <input id="raisingAmount" v-model="writeRaisingAmount" type="number" />
      </label>

      <label for="minMixedTokenAmount">
        Min Mixed Token Amount:
        <input id="minMixedTokenAmount" v-model="writeMinMixedTokenAmount" type="number" />
      </label>
      <label for="raisingAddress">
        Raising Address:
        <input id="raisingAddress" v-model="writeRaisingAddress" type="text" />
      </label>
      <button type="submit">Write</button>
    </form>
    <p>Mint Result: {{ writeMintResult }}</p>
    <p>Burn Result: {{ writeBurnResult }}</p>
  </div>
</template>

<script lang="ts" setup>
import { mixedToken } from '@solio/core';
import { Address, formatEther, parseEther, zeroAddress } from 'viem';
import { ref } from 'vue';
import { readClient, writeClient } from '../constant';

const readAddress = ref<Address>('' as Address);
const readRaisingToken = ref('');
const readAdmin = ref('');
const readMetadata = ref('');
const readTaxRate = ref('');
const readTreasury = ref('');
const readEstimateMint = ref('');
const readEstimateBurn = ref('');
const readEstimateMintNeed = ref('');

const writeAddress = ref<Address>('' as Address);
const writeRaisingAmount = ref(0);
const writeMinMixedTokenAmount = ref(0);
const writeRaisingAddress = ref<Address>('' as Address);
const writeMintResult = ref('');
const writeBurnResult = ref('');

const handleReadSubmit = async () => {
  const result = await mixedToken.read.getRaisingToken(readClient, {
    address: readAddress.value,
  });
  readRaisingToken.value = result;

  const admin = await mixedToken.read.getAdmin(readClient, {
    address: readAddress.value,
  });
  readAdmin.value = admin;

  const metadata = await mixedToken.read.getMetadata(readClient, {
    address: readAddress.value,
  });
  readMetadata.value = metadata;

  const taxRate = await mixedToken.read.getTaxRate(readClient, {
    address: readAddress.value,
  });
  readTaxRate.value = JSON.stringify(taxRate);

  const treasury = await mixedToken.read.getTreasury(readClient, {
    address: readAddress.value,
  });
  readTreasury.value = treasury;

  const estimateMint = await mixedToken.read.getEstimateMint(readClient, {
    address: readAddress.value,
    raisingAmount: parseEther('10'),
  });
  readEstimateMint.value = formatEther(estimateMint.mixedTokenAmount);

  const estimateBurn = await mixedToken.read.getEstimateBurn(readClient, {
    address: readAddress.value,
    mixedTokenAmount: parseEther('10000'),
  });
  readEstimateBurn.value = formatEther(estimateBurn.raisingAmount);

  const estimateMintNeed = await mixedToken.read.getEstimateMintNeed(readClient, {
    address: readAddress.value,
    mixedTokenAmount: parseEther('10000'),
  });
  readEstimateMintNeed.value = formatEther(estimateMintNeed.raisingAmount);
};

const handleWriteSubmit = async () => {
  const mintResult = await mixedToken.write.mint(writeClient, {
    address: writeAddress.value,
    raisingAmount: parseEther(writeRaisingAmount.value.toString()),
    raisingAddress: writeRaisingAddress.value,
    minMixedTokenAmount: 0n,
  });
  writeMintResult.value = mintResult;

  const burnResult = await mixedToken.write.burn(writeClient, {
    address: writeAddress.value,
    raisingAmount: parseEther(writeRaisingAmount.value.toString()),
    minMixedTokenAmount: parseEther(writeMinMixedTokenAmount.value.toString()),
  });
  writeBurnResult.value = burnResult;
};
</script>

// examples/vite-react/src/components/mixed-token.tsx
import { formatSafeToString, mixedToken } from '@solio/core';
import { useState } from 'react';
import { Address, type WriteContractErrorType, parseEther } from 'viem';
import { readClient, writeClient } from '../constant';

export const MixedToken = () => {
  const [address, setAddress] = useState<Address>('' as Address);
  const [raisingAddress, setRaisingAddress] = useState<Address>('' as Address);
  const [raisingAmount, setRaisingAmount] = useState('');
  const [minMixedTokenAmount, setMinMixedTokenAmount] = useState('');
  const [result, setResult] = useState('');

  const getRaisingToken = async () => {
    try {
      const result = await mixedToken.read.getRaisingToken(readClient, {
        address,
      });
      setResult(formatSafeToString(result));
    } catch (error: unknown) {
      const err = error as WriteContractErrorType;
      console.log('getRaisingToken error', err.name);
    }
  };

  const getAdmin = async () => {
    try {
      const result = await mixedToken.read.getAdmin(readClient, {
        address,
      });
      setResult(formatSafeToString(result));
    } catch (error: unknown) {
      const err = error as WriteContractErrorType;
      console.log('getAdmin error', err.name);
    }
  };

  const getMetadata = async () => {
    try {
      const result = await mixedToken.read.getMetadata(readClient, {
        address,
      });
      setResult(formatSafeToString(result));
    } catch (error: unknown) {
      const err = error as WriteContractErrorType;
      console.log('getMetadata error', err.name);
    }
  };

  const getTaxRate = async () => {
    try {
      const result = await mixedToken.read.getTaxRate(readClient, {
        address,
      });
      setResult(`Mint Tax: ${result.mintTax}, Burn Tax: ${result.burnTax}`);
    } catch (error: unknown) {
      const err = error as WriteContractErrorType;
      console.log('getTaxRate error', err.name);
    }
  };

  const getTreasury = async () => {
    try {
      const result = await mixedToken.read.getTreasury(readClient, {
        address,
      });
      setResult(formatSafeToString(result));
    } catch (error: unknown) {
      const err = error as WriteContractErrorType;
      console.log('getTreasury error', err.name);
    }
  };

  const getEstimateMint = async () => {
    try {
      const result = await mixedToken.read.getEstimateMint(readClient, {
        address,
        raisingAmount: parseEther(raisingAmount),
      });
      setResult(formatSafeToString(result.mixedTokenAmount));
    } catch (error: unknown) {
      const err = error as WriteContractErrorType;
      console.log('getEstimateMint error', err.name);
    }
  };

  const getEstimateBurn = async () => {
    try {
      const result = await mixedToken.read.getEstimateBurn(readClient, {
        address,
        mixedTokenAmount: parseEther(minMixedTokenAmount),
      });
      setResult(formatSafeToString(result.raisingAmount));
    } catch (error: unknown) {
      const err = error as WriteContractErrorType;
      console.log('getEstimateBurn error', err.name);
    }
  };

  const getEstimateMintNeed = async () => {
    try {
      const result = await mixedToken.read.getEstimateMintNeed(readClient, {
        address,
        mixedTokenAmount: parseEther(minMixedTokenAmount),
      });
      setResult(formatSafeToString(result.raisingAmount));
    } catch (error: unknown) {
      const err = error as WriteContractErrorType;
      console.log('getEstimateMintNeed error', err.name);
    }
  };

  const mint = async () => {
    try {
      const result = await mixedToken.write.mint(writeClient, {
        address,
        raisingAmount: parseEther(raisingAmount),
        minMixedTokenAmount: parseEther(minMixedTokenAmount),
        raisingAddress,
      });
      setResult(formatSafeToString(result));
    } catch (error: unknown) {
      const err = error as WriteContractErrorType;
      console.log('mint error', err.name);
    }
  };

  const burn = async () => {
    try {
      const result = await mixedToken.write.burn(writeClient, {
        address,
        minMixedTokenAmount: parseEther(minMixedTokenAmount),
        raisingAmount: parseEther(raisingAmount),
      });
      setResult(formatSafeToString(result));
    } catch (error: unknown) {
      const err = error as WriteContractErrorType;
      console.log('burn error', err.name);
    }
  };

  return (
    <div>
      <h2>Mixed Token Contract</h2>
      <input
        type="text"
        value={address}
        maxLength={42}
        minLength={42}
        onChange={(e) => setAddress(e.target.value as Address)}
        placeholder="Address"
      />
      <input
        type="text"
        value={raisingAddress}
        onChange={(e) => setRaisingAddress(e.target.value as Address)}
        placeholder="Raising Address"
      />
      <input
        type="text"
        value={raisingAmount}
        onChange={(e) => setRaisingAmount(e.target.value)}
        placeholder="Raising Amount"
      />
      <input
        type="text"
        value={minMixedTokenAmount}
        onChange={(e) => setMinMixedTokenAmount(e.target.value)}
        placeholder="Min Mixed Token Amount"
      />
      <button onClick={getRaisingToken}>Get Raising Token</button>
      <button onClick={getAdmin}>Get Admin</button>
      <button onClick={getMetadata}>Get Metadata</button>
      <button onClick={getTaxRate}>Get Tax Rate</button>
      <button onClick={getTreasury}>Get Treasury</button>
      <button onClick={getEstimateMint}>Get Estimate Mint</button>
      <button onClick={getEstimateBurn}>Get Estimate Burn</button>
      <button onClick={getEstimateMintNeed}>Get Estimate Mint Need</button>
      <button onClick={mint}>Mint</button>
      <button onClick={burn}>Burn</button>
      <p>Result: {result}</p>
    </div>
  );
};

export default MixedToken;
