// examples/vite-vue/src/components/router.vue
<template>
  <div>
    <h1>Router</h1>
    <form>
      <label>
        Contract Address:
        <input v-model="address" type="text" :placeholder="zeroAddress" />
      </label>
      <label>
        Pay Address:
        <input v-model="payAddress" type="text" :placeholder="zeroAddress" />
      </label>
      <label>
        Receive Address:
        <input v-model="receiveAddress" type="text" :placeholder="zeroAddress" />
      </label>
      <label>
        Pay Amount:
        <input v-model="payAmount" type="text" placeholder="" />
      </label>
      <label>
        Receive Amount:
        <input v-model="receiveAmount" type="text" placeholder="" />
      </label>
      <label>
        Raising Amount:
        <input v-model="raisingAmount" type="text" placeholder="" />
      </label>
      <label>
        Raising Token:
        <input v-model="raisingToken" type="text" placeholder="" />
      </label>
      <label>
        Mixed Token Index:
        <input v-model="mixedTokenIndex" type="text" placeholder="" />
      </label>
      <label>
        Min Mixed Token Amount:
        <input v-model="minMixedTokenAmount" type="text" placeholder="" />
      </label>
      <label>
        Pay Index:
        <input v-model="payIndex" type="text" placeholder="" />
      </label>
      <label>
        Receive Index:
        <input v-model="receiveIndex" type="text" placeholder="" />
      </label>
      <label>
        Min Receive Amount:
        <input v-model="minReceiveAmount" type="text" placeholder="" />
      </label>
      <label>
        Admin Address:
        <input v-model="adminAddress" type="text" placeholder="" />
      </label>
      <button @click="getFactory">Get Factory</button>
      <button @click="getAmountOut">Get Amount Out</button>
      <button @click="mint">Mint</button>
      <button @click="swap">Swap</button>
    </form>
    <p>Result: {{ result }}</p>
  </div>
</template>

<script setup lang="ts">
import { router } from '@solio/core';
import { Address, parseEther, zeroAddress } from 'viem';
import { ref } from 'vue';
import { readClient, writeClient } from '../constant';

const address = ref<Address>('' as Address);
const payAddress = ref<Address>('' as Address);
const receiveAddress = ref<Address>('' as Address);
const payAmount = ref('');
const receiveAmount = ref('');
const raisingAmount = ref('');
const raisingToken = ref<Address>('' as Address);
const mixedTokenIndex = ref('');
const minMixedTokenAmount = ref('');
const payIndex = ref('');
const receiveIndex = ref('');
const minReceiveAmount = ref('');
const adminAddress = ref<Address>('' as Address);
const result = ref('');

const getFactory = async () => {
  const resultValue = await router.read.getFactory(readClient, {
    address: address.value,
  });
  result.value = `Get Factory: ${resultValue}`;
};

const getAmountOut = async () => {
  const { receiveAmount: receiveAmountValue, raisingAmount: raisingAmountValue } = await router.read.getAmountOut(
    readClient,
    {
      address: address.value,
      payAddress: payAddress.value,
      receiveAddress: receiveAddress.value,
      payAmount: parseEther(payAmount.value),
    },
  );
  result.value = `Get Amount Out: receiveAmount=${receiveAmountValue}, raisingAmount=${raisingAmountValue}`;
};

const mint = async () => {
  const resultValue = await router.write.mint(writeClient, {
    address: address.value,
    raisingToken: raisingToken.value,
    raisingAmount: parseEther(raisingAmount.value),
    mixedTokenIndex: BigInt(mixedTokenIndex.value),
    minMixedTokenAmount: parseEther(minMixedTokenAmount.value),
  });
  result.value = `Mint: ${resultValue}`;
};

const swap = async () => {
  const resultValue = await router.write.swap(writeClient, {
    address: address.value,
    raisingToken: raisingToken.value,
    payAddress: payAddress.value,
    payIndex: BigInt(payIndex.value),
    payAmount: parseEther(payAmount.value),
    receiveAddress: receiveAddress.value,
    receiveIndex: BigInt(receiveIndex.value),
    minReceiveAmount: parseEther(minReceiveAmount.value),
  });
  result.value = `Swap: ${resultValue}`;
};
</script>

// examples/vite-react/src/components/router.tsx
import { router } from '@solio/core';
import { useState } from 'react';
import { Address, parseEther } from 'viem';
import { readClient, writeClient } from '../constant';

const Router = () => {
  const [factoryAddress, setFactoryAddress] = useState<Address>('' as Address);
  const [receiveAmount, setReceiveAmount] = useState('');
  const [raisingAmount, setRaisingAmount] = useState('');
  const [result, setResult] = useState('');

  const [mixedTokenIndex, setMixedTokenIndex] = useState('');
  const [minMixedTokenAmount, setMinMixedTokenAmount] = useState('');
  const [routerAddress, setRouterAddress] = useState<Address>('' as Address);
  const [raisingToken, setRaisingToken] = useState<Address>('' as Address);
  const [payAddress, setPayAddress] = useState<Address>('' as Address);
  const [payIndex, setPayIndex] = useState('');
  const [payAmount, setPayAmount] = useState('');
  const [receiveAddress, setReceiveAddress] = useState<Address>('' as Address);
  const [receiveIndex, setReceiveIndex] = useState('');
  const [minReceiveAmount, setMinReceiveAmount] = useState('');

  const handleGetFactory = async () => {
    const result = await router.read.getFactory(readClient, {
      address: routerAddress,
    });
    setFactoryAddress(result.toLowerCase() as Address);
  };

  const handleGetAmountOut = async () => {
    const result = await router.read.getAmountOut(readClient, {
      address: routerAddress,
      payAddress,
      receiveAddress,
      payAmount: parseEther(payAmount),
    });
    setReceiveAmount(result.receiveAmount.toString());
    setRaisingAmount(result.raisingAmount.toString());
  };

  const handleMint = async () => {
    const result = await router.write.mint(writeClient, {
      address: routerAddress,
      raisingToken,
      raisingAmount: parseEther(raisingAmount),
      mixedTokenIndex: BigInt(mixedTokenIndex),
      minMixedTokenAmount: parseEther(minMixedTokenAmount),
    });
    setResult(result);
  };

  const handleSwap = async () => {
    const result = await router.write.swap(writeClient, {
      address: routerAddress,
      raisingToken,
      payAddress,
      payIndex: BigInt(payIndex),
      payAmount: parseEther(payAmount),
      receiveAddress,
      receiveIndex: BigInt(receiveIndex),
      minReceiveAmount: parseEther(minReceiveAmount),
    });
    setResult(result);
  };

  return (
    <div>
      <h2>Router Contract</h2>
      <input
        type="text"
        value={routerAddress}
        onChange={(e) => setRouterAddress(e.target.value as Address)}
        placeholder="Router Address"
      />
      <input
        type="text"
        value={raisingToken}
        onChange={(e) => setRaisingToken(e.target.value as Address)}
        placeholder="Raising Token"
      />
      <input
        type="text"
        value={raisingToken}
        onChange={(e) => setMixedTokenIndex(e.target.value as Address)}
        placeholder="Mixed Token Index"
      />
      <input
        type="text"
        value={raisingToken}
        onChange={(e) => setMinMixedTokenAmount(e.target.value as Address)}
        placeholder="Min Mixed Token Amount"
      />
      <input
        type="text"
        value={payAddress}
        onChange={(e) => setPayAddress(e.target.value as Address)}
        placeholder="Pay Address"
      />
      <input type="text" value={payIndex} onChange={(e) => setPayIndex(e.target.value)} placeholder="Pay Index" />
      <input type="text" value={payAmount} onChange={(e) => setPayAmount(e.target.value)} placeholder="Pay Amount" />
      <input
        type="text"
        value={receiveAddress}
        onChange={(e) => setReceiveAddress(e.target.value as Address)}
        placeholder="Receive Address"
      />
      <input type="text" value={receiveIndex} onChange={(e) => setReceiveIndex(e.target.value)} placeholder="Receive Index" />
      <input
        type="text"
        value={minReceiveAmount}
        onChange={(e) => setMinReceiveAmount(e.target.value)}
        placeholder="Min Receive Amount"
      />
      <button onClick={handleGetFactory}>Get Factory</button>
      <button onClick={handleGetAmountOut}>Get Amount Out</button>
      <button onClick={handleMint}>Mint</button>
      <button onClick={handleSwap}>Swap</button>
      <p>Factory Address: {factoryAddress}</p>
      <p>Receive Amount: {receiveAmount}</p>
      <p>Raising Amount: {raisingAmount}</p>
      <p>Result: {result}</p>
    </div>
  );
};

export default Router;
